# Generated by Django 3.2 on 2021-06-21 08:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Id única para la categoría', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('apellido_m', models.CharField(max_length=200)),
                ('nombre_tienda', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['rut'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=8)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.categoria')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
    ]
