# Generated by Django 3.2 on 2021-06-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre_tienda']},
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
