# Generated by Django 3.2 on 2021-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id_carro', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'carro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cate', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comu', models.IntegerField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=150)),
                ('precio', models.CharField(max_length=8)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('apellido_m', models.CharField(max_length=150)),
                ('nombre_tienda', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_tipo', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('apellido_m', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
