# Generated by Django 3.2 on 2021-06-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_productos_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_p', models.CharField(max_length=200)),
                ('apellido_m', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
