# Generated by Django 3.2 on 2021-06-22 02:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['comuna'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['region'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.region'),
        ),
    ]
