# Generated by Django 3.2 on 2021-06-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20210622_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.comuna'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.region'),
        ),
    ]
