# Generated by Django 3.2 on 2021-06-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_region_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='comuna',
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.region'),
        ),
    ]
