# Generated by Django 3.2 on 2021-06-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20210623_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ['region']},
        ),
    ]
