# Generated by Django 3.2 on 2021-06-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alter_comuna_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ['comuna']},
        ),
    ]
